/* LoveLoop API contracts: every couple-scoped operation is protected by the authenticated Manus user. */
import { COOKIE_NAME } from "@shared/const";
import { TRPCError } from "@trpc/server";
import { eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { storagePut } from "./storage";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { couples, dailyChallenges, gameSessions, invites, memories, messages, notifications, getActiveGame, getCoupleByInviteCode, getCoupleForUser, getDb, getMemories, getMessages, getNotifications, getTodaysChallenge } from "./db";

const challengePrompt = "Send each other a voice note describing your perfect day together.";
const today = () => new Date().toISOString().slice(0, 10);
async function requireCouple(userId: number) { const couple = await getCoupleForUser(userId); if (!couple) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Create or join a LoveLoop first." }); return couple; }

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  couple: router({
    mine: protectedProcedure.query(({ ctx }) => getCoupleForUser(ctx.user.id)),
    create: protectedProcedure.input(z.object({ partnerAName: z.string().max(120).optional(), partnerBName: z.string().max(120).optional(), relationshipDuration: z.string().max(64).optional(), relationshipStyle: z.string().max(64).optional(), startedAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { const existing = await getCoupleForUser(ctx.user.id); if (existing) return existing; const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await db.insert(couples).values({ partnerAId: ctx.user.id, partnerAName: input.partnerAName, partnerBName: input.partnerBName, relationshipDuration: input.relationshipDuration, inviteCode: nanoid(10), relationshipStyle: input.relationshipStyle, startedAt: input.startedAt }); const saved = await getCoupleForUser(ctx.user.id); if (!saved) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Couple was not created" }); return saved; }),
    invite: protectedProcedure.input(z.object({ email: z.string().email().optional() })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const token = nanoid(32); await db.insert(invites).values({ coupleId: couple.id, inviterId: ctx.user.id, email: input.email, token, expiresAt: new Date(Date.now() + 7 * 86400000) }); return { token, inviteCode: couple.inviteCode, inviteUrl: `${process.env.VITE_APP_URL || ""}/?invite=${couple.inviteCode}` }; }),
    accept: protectedProcedure.input(z.object({ inviteCode: z.string().min(4) })).mutation(async ({ ctx, input }) => { const couple = await getCoupleByInviteCode(input.inviteCode); if (!couple) throw new TRPCError({ code: "NOT_FOUND", message: "Invite not found" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(couples).set({ partnerBId: ctx.user.id }).where(eq(couples.id, couple.id)); return { success: true, coupleId: couple.id } as const; }),
  }),
  dashboard: router({
    snapshot: protectedProcedure.query(async ({ ctx }) => { const couple = await requireCouple(ctx.user.id); let challenge: any = await getTodaysChallenge(couple.id, today()); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); if (!challenge) { const [row] = await db.insert(dailyChallenges).values({ coupleId: couple.id, prompt: challengePrompt, category: "deep", challengeDate: today(), durationMinutes: 10 }).$returningId(); challenge = { id: row.id, coupleId: couple.id, prompt: challengePrompt, category: "deep", challengeDate: today(), durationMinutes: 10, completedAt: null, completedBy: null, createdAt: new Date() } as typeof challenge; } return { couple, challenge, memories: await getMemories(couple.id), messages: await getMessages(couple.id), notifications: await getNotifications(ctx.user.id) }; }),
    completeChallenge: protectedProcedure.input(z.object({ challengeId: z.number() })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(dailyChallenges).set({ completedAt: new Date(), completedBy: ctx.user.id }).where(eq(dailyChallenges.id, input.challengeId)); await db.update(couples).set({ streak: couple.streak + 1, xp: couple.xp + 120 }).where(eq(couples.id, couple.id)); const partnerId = couple.partnerAId === ctx.user.id ? couple.partnerBId : couple.partnerAId; if (partnerId) await db.insert(notifications).values({ userId: partnerId, coupleId: couple.id, kind: "challenge_completed", body: "Your partner just completed today’s loop." }); return { success: true, xpAwarded: 120 }; }),
  }),
  messages: router({ list: protectedProcedure.query(async ({ ctx }) => getMessages((await requireCouple(ctx.user.id)).id)), send: protectedProcedure.input(z.object({ body: z.string().min(1).max(2000) })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [row] = await db.insert(messages).values({ coupleId: couple.id, senderId: ctx.user.id, body: input.body }).$returningId(); const partnerId = couple.partnerAId === ctx.user.id ? couple.partnerBId : couple.partnerAId; if (partnerId) await db.insert(notifications).values({ userId: partnerId, coupleId: couple.id, kind: "message", body: "Your partner sent you a new message." }); return { id: row.id, body: input.body }; }) }),
  memories: router({ list: protectedProcedure.query(async ({ ctx }) => getMemories((await requireCouple(ctx.user.id)).id)), create: protectedProcedure.input(z.object({ title: z.string().min(1).max(180), type: z.enum(["photo", "video", "voice", "letter", "challenge"]), note: z.string().max(2000).optional(), fileKey: z.string().max(512).optional(), url: z.string().url().optional() })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [row] = await db.insert(memories).values({ ...input, coupleId: couple.id, creatorId: ctx.user.id }); return { success: true, id: row.insertId }; }) }),
  notifications: router({ list: protectedProcedure.query(({ ctx }) => getNotifications(ctx.user.id)), markRead: protectedProcedure.input(z.object({ id: z.number() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(notifications).set({ readAt: new Date() }).where(eq(notifications.id, input.id)); return { success: true }; }) }),
  media: router({ uploadMemory: protectedProcedure.input(z.object({ title: z.string().min(1).max(180), type: z.enum(["photo", "video", "voice", "letter", "challenge"]), fileName: z.string().max(180), contentType: z.string().max(120), dataBase64: z.string().min(1), note: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const uploaded = await storagePut(`${couple.id}/${ctx.user.id}/${input.fileName}`, Buffer.from(input.dataBase64, "base64"), input.contentType); const [row] = await db.insert(memories).values({ coupleId: couple.id, creatorId: ctx.user.id, title: input.title, type: input.type, fileKey: uploaded.key, url: uploaded.url, note: input.note }); return { id: row.insertId, url: uploaded.url }; }) }),
  games: router({ active: protectedProcedure.query(async ({ ctx }) => getActiveGame((await requireCouple(ctx.user.id)).id)), start: protectedProcedure.input(z.object({ gameType: z.string().max(48) })).mutation(async ({ ctx, input }) => { const couple = await requireCouple(ctx.user.id); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [row] = await db.insert(gameSessions).values({ coupleId: couple.id, gameType: input.gameType }); return { id: row.insertId, gameType: input.gameType, currentQuestion: 0 }; }), answer: protectedProcedure.input(z.object({ sessionId: z.number(), answer: z.string().max(1000), partner: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(gameSessions).set(input.partner ? { answerB: input.answer, currentQuestion: 1 } : { answerA: input.answer }).where(eq(gameSessions.id, input.sessionId)); return { success: true }; }) }),
});
export type AppRouter = typeof appRouter;
